runtime: python
env: flex
entrypoint: python -m app.main

runtime_config:
    python_version: 3

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 15

resources:
    cpu: 1
    memory_gb: 0.5
    disk_size_gb: 10
